# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.7.0
_src_path: git+https://github.com/OCA/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 13.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Odoo Estonian Localization
repo_name: Odoo Estonian Localization
repo_slug: l10n-estonia
repo_website: https://github.com/OCA/l10n-estonia
travis_apt_packages: []
travis_apt_sources: []

